/**
 * Книжный магазин
 * Сервер книжного магазина
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BookAuthor } from './bookAuthor';
import { BookSeries } from './bookSeries';
import { Category } from './category';
import { City } from './city';
import { Language } from './language';
import { Publisher } from './publisher';


/**
 * книга
 */
export interface Book {
  /**
   * уникальный идентификатор книги
   */
  id?: number;
  /**
   * название книги
   */
  title?: string;
  subtitle?: string;
  /**
   * номер издания
   */
  edition?: number;
  /**
   * международный стандартный книжный номер
   */
  ISBN?: string;
  /**
   * индекс Универсальной десятичной классификации
   */
  UDC?: string;
  /**
   * индекс Библиотечно - библиографической классификации
   */
  BBK?: string;
  /**
   * авторский знак
   */
  cutterCode?: string;
  /**
   * год издания
   */
  publicationYear?: Date;
  /**
   * тираж
   */
  circulation?: number;
  /**
   * цена
   */
  price?: number;
  /**
   * в наличии
   */
  inStock?: number;
  /**
   * издательство
   */
  publisher?: Publisher;
  /**
   * авторы книги
   */
  authors?: BookAuthor[];
  /**
   * город издания
   */
  city?: City;
  /**
   * язык издания
   */
  language?: Language;
  /**
   * серия книг
   */
  bookSeries?: BookSeries;
  /**
   * категории(жанр) книги
   */
  categories?: Category[];
}
