/**
 * Книжный магазин
 * Сервер книжного магазина
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Book } from './book';


/**
 * Элемент корзины или заказа (одна позиция в корзине или заказе)
 */
export interface OrderItem {
  /**
  * уникальный идентификатор элемента корзины
  */
  id?: number;
  /**
   * Книга
   */
  book?: Book;
  /**
   * Количество
   */
  count?: number;
}
