/**
 * Книжный магазин
 * Сервер книжного магазина
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * автор
 */
export interface Person {
  /**
   * уникальный идентификатор автора
   */
  id?: number;
  /**
   * Имя
   */
  firstName?: string;
  /**
   * Отчество
   */
  middleName?: string;
  /**
   * Фамилия
   */
  lastName?: string;
}
