import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

/**
 * Книжный магазин
 * Сервер книжного магазина
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * город издания
 */
@Entity()
export class City {
  /**
   * уникальный идентификатор города
   */
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  deleted: boolean;

  /**
   * название города
   */
  @Column()
  name: string;

  /**
   * код города
   */
  @Column()
  codeName: string;
}
