/**
 * Книжный магазин
 * Сервер книжного магазина
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * город издания
 */
export interface City {
  /**
   * уникальный идентификатор города
   */
  id?: number;
  deleted?: boolean;
  /**
   * название города
   */
  name?: string;
  /**
   * код города
   */
  codeName?: string;
}
