/**
 * Книжный магазин
 * Сервер книжного магазина
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * язык книги
 */
export interface Language {
  /**
   * уникальный идентификатор языка
   */
  id?: number;
  deleted?: boolean;
  /**
   * название языка
   */
  name?: string;
  /**
   * код языка
   */
  codeName?: string;
}
